import tskit

NODE_IS_SAMPLE = tskit.NODE_IS_SAMPLE  # noqa: F401
NULL = tskit.NULL  # noqa: F401
IEDGES_ONE_PARENT_PER_POSITION = 1 << 3  # noqa: F401
IEDGES_VALID_INTERVALS = 1 << 4  # noqa: F401
IEDGES_CHILD_IDS_ADJACENT = 1 << 5  # noqa: F401
IEDGES_PARENT_OLDER_THAN_CHILD = 1 << 6  # noqa: F401
VALID_GIG = (
    IEDGES_VALID_INTERVALS | IEDGES_PARENT_OLDER_THAN_CHILD | IEDGES_CHILD_IDS_ADJACENT
)

ROOTWARDS = 0
LEAFWARDS = 1
