import tskit

NODE_IS_SAMPLE = tskit.NODE_IS_SAMPLE  # noqa: F401
NULL = tskit.NULL  # noqa: F401
IEDGES_CHILD_LEFT_LESS_THAN_RIGHT = 1 << 5  # noqa: F401
IEDGES_PARENT_OLDER_THAN_CHILD = 1 << 6  # noqa: F401
VALID_GIG = IEDGES_CHILD_LEFT_LESS_THAN_RIGHT | IEDGES_PARENT_OLDER_THAN_CHILD

ROOTWARDS = 0
LEAFWARDS = 1
